
import webview
import sys
import os
import json
from python.db import db
from python.services.data_mapper import DataMapper
from python.services.pdf_generator import PdfGenerator

# Ustawienie ścieżki do plików Reacta (build)
# W trybie DEV: http://localhost:3000
# W trybie PROD: ścieżka do folderu dist/
REACT_DEV_URL = "http://localhost:3000"
REACT_BUILD_DIR = os.path.join(os.path.dirname(os.path.dirname(__file__)), "dist")

class Api:
    """
    Most między JavaScript (React) a Pythonem.
    W React wywołujesz: window.pywebview.api.metoda(arg)
    """
    
    def __init__(self):
        self._window = None

    def set_window(self, window):
        self._window = window

    # --- 1. CORE DATA ---
    def get_clients(self):
        """Pobiera klientów z SQLite"""
        print("[PY] Pobieranie klientów...")
        return db.get_all_clients()

    def save_client(self, client_data):
        """Zapisuje klienta z Reacta do SQLite"""
        print(f"[PY] Zapis klienta: {client_data.get('lastName')}")
        db.add_client(client_data)
        return {"status": "ok", "id": client_data.get('id')}

    # --- 2. OPERACJE NA PLIKACH (LISP / PDF) ---
    def generate_lisp(self, polyline_data):
        """Generuje plik LISP dla CADa"""
        try:
            # Tu logika generowania pliku .lsp
            filename = f"droga_{uuid.uuid4().hex[:4]}.lsp"
            path = os.path.abspath(filename)
            with open(path, "w", encoding="cp1250") as f:
                f.write(f'; Generated by Drogowiec\n(defun c:rysuj () ...)')
            
            return {"status": "ok", "path": path}
        except Exception as e:
            return {"status": "error", "message": str(e)}

    def generate_termination_pdf(self, term_data):
        """Generuje PDF wypowiedzenia"""
        try:
            # Logika mapowania danych z Reacta do generatora PDF
            output_path = os.path.abspath(f"wypowiedzenie_{term_data.get('id')}.pdf")
            
            # Mock danych dla generatora (w produkcji przekaż pełne dane)
            client = {'firstName': 'Jan', 'lastName': 'Test', 'address': 'Ulica 1', 'pesel': '900909'}
            policy = {'policyNumber': '123', 'vehicleBrand': 'Audi', 'vehicleReg': 'GD123'}
            insurer = {'name': 'PZU', 'address': 'Postępu 18', 'zip': '00-000', 'city': 'W-wa'}
            
            PdfGenerator.generate_termination(client, policy, insurer, output_path)
            
            # Otwórz folder z plikiem
            if sys.platform == 'win32':
                os.startfile(os.path.dirname(output_path))
                
            return {"status": "ok", "path": output_path}
        except Exception as e:
            return {"status": "error", "message": str(e)}

    # --- 3. SYSTEMOWE ---
    def minimize_window(self):
        if self._window: self._window.minimize()

    def close_window(self):
        if self._window: self._window.destroy()

def run_app():
    api = Api()
    
    # Decyzja: DEV czy PROD?
    # Sprawdzamy czy folder dist istnieje, jak nie to zakładamy tryb dev
    url = REACT_DEV_URL
    if os.path.exists(os.path.join(REACT_BUILD_DIR, "index.html")):
        # W produkcji wskazujemy na plik
        # url = os.path.join(REACT_BUILD_DIR, "index.html")
        pass # Na razie wymuszamy dev dla wygody testów

    window = webview.create_window(
        'Drogowiec CRM Pro', 
        url=url,
        js_api=api,
        width=1400,
        height=900,
        frameless=False, # True jeśli chcesz własny pasek tytułu w React
        easy_drag=True
    )
    
    api.set_window(window)
    webview.start(debug=True) # debug=True pozwala na F12 (Inspect Element)

if __name__ == '__main__':
    run_app()
